// ===================================================================================
// --- GUAMAHAMMER MODULAR ARMY BUILDER - COMMON MAGIC ITEMS ---
// ===================================================================================
// Last Updated: 2025-09-07 @ 01:30 - Standardized filename
// This file contains magic items available to most armies.

export const commonMagicItemsDB = {
    "Arma Mágica": {
        "Espadón de Muerte": { points: 50, faction: "comunes", relic: true, summary: "Arma 2M. F10. Si hiere, a 4+ recupera 1H." },
        "Espada de Acero Punzante": { points: 40, faction: "comunes", relic: true, summary: "Impacta auto. +1F. Oponente repite TSA superadas." },
        "Espada de los Héroes": { points: 50, faction: "comunes", relic: false, summary: "vs R5+, +3F y Heridas Múltiples(1D3)." },
        "Cuchilla Mortal": { points: 45, faction: "comunes", relic: false, summary: "Niega TSA." },
        "Decapitadora": { points: 45, faction: "comunes", relic: false, summary: "F+1, Impactos Múltiples(2), Poder de Penetración." },
        "Espada Desgarradora": { points: 40, faction: "comunes", relic: false, summary: "+1A, +1 para impactar CaC, repite 1s para herir." },
        "Espada Reliquia": { points: 40, faction: "comunes", relic: false, summary: "HA10, +1F, Ataques Flamígeros." },
        "Quiebracorazas": { points: 40, faction: "comunes", relic: false, summary: "Alabarda. +1F (total +2), Odio, Poder Penetración, oponente repite TSA superadas." },
        "Espada de la Muerte Súbita": { points: 40, faction: "comunes", relic: false, summary: "+1F, Impactos Múltiples(1D3)." },
        "Buscacorazones": { points: 35, faction: "comunes", relic: false, summary: "+1F, repite para impactar fallidas. 6s para herir niegan TSA." },
        "Espada de Acero Encantado": { points: 35, faction: "comunes", relic: false, summary: "+2F, +3I." },
        "Maza Defensora": { points: 35, faction: "comunes", relic: false, summary: "+2HA, +1F. 1 enemigo en contacto -1A. Heridos por la maza -1A." },
        "Espada del Dragón": { points: 35, faction: "comunes", relic: false, summary: "Hiere a 4+ (salvo F>R), I10, Impactos Múltiples(2), Ataques Flamígeros." },
        "Espadas Brujas": { points: 35, faction: "comunes", relic: false, summary: "Sólo hechiceros. +1F por cada nivel de magia." },
        "Espada de Oro Fulgurante": { points: 30, faction: "comunes", relic: false, summary: "+2A, Poder de Penetración." },
        "Dagas Mortales": { points: 30, faction: "comunes", relic: false, summary: "+1A (total +2), +2I, Odio, Golpe Maestro, repite 1s para herir." },
        "Ensartadora": { points: 30, faction: "comunes", relic: false, summary: "Lanza de caballería. Poder Penetración. Por cada herida a la carga, +1A." },
        "Aflicción del Guerrero": { points: 30, faction: "comunes", relic: false, summary: "Alabarda. +2I, Odio, Poder Penetración. Permite parada." },
        "Mangual Aplastador": { points: 25, faction: "comunes", relic: false, summary: "Mangual. Impactos Múltiples(1D3), Poder de Penetración." },
        "Espada de Oro Marino": { points: 25, faction: "comunes", relic: false, summary: "-3 adicional a TSA. Heridos por la espada -1I." },
        "Mayal Danzante": { points: 25, faction: "comunes", relic: false, summary: "Mayal. +2I, repite 1 para impactar fallida. Si hiere 1a ronda, no hay agotamiento." },
        "Lanza Punzante": { points: 20, faction: "comunes", relic: false, summary: "Lanza. Odio, -2 a TSA." },
        "Espada Cabalística Dorada": { points: 20, faction: "comunes", relic: false, summary: "Duplica I (máx 10), Golpe Letal." },
        "Lengua de Dragón": { points: 20, faction: "comunes", relic: false, summary: "+1F, Ataques Flamígeros." },
        "Espada Cazabrujas": { points: 20, faction: "comunes", relic: false, summary: "Resistencia Mágica(2). Por cada herida a hechicero, pierde 1 nivel de magia." },
        "Espada de Plata Fulgurante": { points: 15, faction: "comunes", relic: false, summary: "+1A, Poder de Penetración." },
        "Báculo del Cráneo de Kaloth": { points: 15, faction: "comunes", relic: false, summary: "Arma 2M. Sólo hechiceros. Herido debe chequear L o muere." },
        "Espada Bendita": { points: 15, faction: "comunes", relic: false, summary: "Portador y unidad Inmunes a Psicología, Resistencia Mágica(1)." },
        "Espada Exorcista": { points: 15, faction: "comunes", relic: false, summary: "Heridas Múltiples(1D3) vs No Muertos." },
        "Hacha Veloz": { points: 10, faction: "comunes", relic: false, summary: "Arma 2M. No reduce la Iniciativa." },
        "Espada de la Fuerza": { points: 10, faction: "comunes", relic: false, summary: "+1F." },
        "Espadón Berserker": { points: 10, faction: "comunes", relic: false, summary: "Arma 2M. Furia Asesina (no la pierde)." },
        "Espada Aullante": { points: 5, faction: "comunes", relic: false, summary: "Causa Miedo." }
    },
    "Armadura Mágica": {
        "Armadura del Defensor": { points: 50, faction: "comunes", relic: true, summary: "Armadura pesada. Salvación Especial (4+)." },
        "Escudo Antihechizos": { points: 35, faction: "comunes", relic: true, summary: "Escudo. Resistencia Mágica(3). Si dispersa, mago sufre 1D3 impactos F6." },
        "Armadura de la Robustez": { points: 45, faction: "comunes", relic: false, summary: "Armadura pesada. +2R." },
        "Armadura de los Héroes": { points: 35, faction: "comunes", relic: false, summary: "Armadura de Placas. Salvación Especial (5+)." },
        "Armadura de Sombras": { points: 30, faction: "comunes", relic: false, summary: "Armadura ligera. Esquiva(5+). -1F a impactos en contra." },
        "Armadura de Hierro Meteórico": { points: 25, faction: "comunes", relic: false, summary: "Armadura pesada. TSA de 1+." },
        "Armadura de la Suerte": { points: 15, faction: "comunes", relic: false, summary: "Armadura de Placas. Salvación Especial (6+)." },
        "Escudo de Ptolos": { points: 15, faction: "comunes", relic: false, summary: "Escudo. Salvación Especial (4+ vs proyectiles y máquinas de guerra)." },
        "Escamas Brillantes": { points: 15, faction: "comunes", relic: false, summary: "Armadura Pesada. -1 para impactar al portador en CaC." },
        "Yelmo de Dragón": { points: 10, faction: "comunes", relic: false, summary: "+1 a TSA, Inmune a Fuego." },
        "Escudo Rúnico": { points: 5, faction: "comunes", relic: false, summary: "Escudo. Tras salvar en CaC, atacante sufre impacto F4." },
        "Escudo Encantado": { points: 5, faction: "comunes", relic: false, summary: "Escudo. +1 a TSA." }
    },
    "Talismán": {
        "Talismán del Destino": { points: 45, faction: "comunes", relic: true, summary: "Salvación Especial (4+)." },
        "Amuleto Negro": { points: 25, faction: "comunes", relic: true, summary: "Salvación Especial (5+). Tras salvar en CaC, atacante sufre herida sin TSA." },
        "Pintura de Guerra Mágica": { points: 30, faction: "comunes", relic: false, summary: "Salvación Especial (5+), Resistencia Mágica(1). No puede llevar armadura/escudo." },
        "Brazales del Rayo": { points: 25, faction: "comunes", relic: false, summary: "Salvación Especial (4+ vs proyectiles y hechizos de Proyectil Mágico/Daño Directo)." },
        "Talismán de Resistencia": { points: 25, faction: "comunes", relic: false, summary: "Salvación Especial (5+)." },
        "Semilla de renacimiento": { points: 25, faction: "comunes", relic: false, summary: "Regeneración (5+)." },
        "Amuleto Ámbar": { points: 20, faction: "comunes", relic: false, summary: "Inicio de turno propio, si está herido, recupera 1H." },
        "Corazón de Obsidiana": { points: 20, faction: "comunes", relic: false, summary: "Resistencia Mágica(2)." },
        "La Piedra del Amanecer": { points: 15, faction: "comunes", relic: false, summary: "Salvación Especial (6+), repite TSA fallidas." },
        "Amuleto Jade": { points: 15, faction: "comunes", relic: false, summary: "Un solo uso. Salvación Especial (2+) contra una única herida." },
        "Gema del Fuego": { points: 10, faction: "comunes", relic: false, summary: "Inmune a Fuego y Veneno. Un solo uso vs primera herida: Salvación Especial (5+)." },
        "Piedra de Obsidiana": { points: 10, faction: "comunes", relic: false, summary: "Resistencia Mágica(1)." },
        "Amuleto del Fuego": { points: 5, faction: "comunes", relic: false, summary: "Un solo uso. Antes de dispersar, gana Resistencia Mágica(3) contra ese hechizo." },
        "Amuleto de la Suerte": { points: 5, faction: "comunes", relic: false, summary: "Un solo uso. Repite un único dado de una tirada que solo le afecte a él." }
    },
    "Artefacto Arcano": {
        "El Libro de Ashur": { points: 50, faction: "comunes", relic: true, summary: "Señor del Conocimiento de un saber a elegir (8 saberes, Magia Oscura o Alta Magia)." },
        "Báculo del Rayo": { points: 40, faction: "comunes", relic: false, summary: "Portahechizos(5). Proyectil mágico 24\", 1D6 impactos F6 sin TSA." },
        "Pergamino de Destrucción de Magia": { points: 40, faction: "comunes", relic: false, summary: "Un solo uso. Dispersa auto hechizo. A 4+, el hechizo se destruye. No vs Fuerza Irresistible." },
        "Báculo Llameante de la Muerte": { points: 35, faction: "comunes", relic: false, summary: "Portahechizos(5). Proyectil mágico 24\", 2D6 impactos F4 (sólo flamígeros).\nCausa Pánico." },
        "Báculo de Azabache": { points: 30, faction: "comunes", relic: false, summary: "Añade 1 dado para lanzar hechizos. Si sale un 1, el báculo se agota." },
        "Vara Terrenal": { points: 25, faction: "comunes", relic: false, summary: "Un solo uso. Ignora una disfunción mágica." },
        "Pergamino de Dispersión de Magia": { points: 25, faction: "comunes", relic: false, summary: "Un solo uso. Dispersa auto hechizo. No vs Fuerza Irresistible." },
        "Báculo del Cráneo": { points: 25, faction: "comunes", relic: false, summary: "+1 a dispersar. 1/turno, personaje a 24\" revela sus objetos mágicos." },
        "Familiar Energético": { points: 20, faction: "comunes", relic: false, summary: "Genera +1 dado de energía (sólo para él)." },
        "Varita del Poder": { points: 20, faction: "comunes", relic: false, summary: "Guarda hasta 2 dados no usados para fases posteriores." },
        "Familiar Hechicero": { points: 15, faction: "comunes", relic: false, summary: "Conoce 1 hechizo adicional." },
        "Poción de Sabiduría": { points: 15, faction: "comunes", relic: false, summary: "Un solo uso. Al inicio de fase de magia, gana 1D3+1 dados de energía." },
        "Pergamino de Energía": { points: 10, faction: "comunes", relic: false, summary: "Un solo uso. Lanza un hechizo con su dificultad básica sin gastar dados." },
        "Cáliz de la Hechicería": { points: 10, faction: "comunes", relic: false, summary: "Canaliza a 2+. Con un 1 natural, sufre 1H sin TSA." },
        "Familiar Guerrero": { points: 10, faction: "comunes", relic: false, summary: "2A adicionales con HA5, F5, I10." },
        "Bastón Negro": { points: 5, faction: "comunes", relic: false, summary: "+1 a canalizar." }
    },
    "Objeto Hechizado": {
        "Anillo de Corin": { points: 30, faction: "comunes", relic: true, summary: "Portahechizos(10). Daño directo vs personaje a 12\".\n1 impacto F4, revela y destruye 1 objeto mágico al azar." },
        "El Cáliz de Rubíes": { points: 25, faction: "comunes", relic: true, summary: "-1 para impactar con disparos a la unidad. -1 para impactar en CaC al portador." },
        "Corona del Poder": { points: 45, faction: "comunes", relic: false, summary: "Tozudez." },
        "Gema Negra de Gnar": { points: 35, faction: "comunes", relic: false, summary: "Un solo uso. En un desafío, retira a ambos combatientes. Regresan a 6+ en 1D6 (+1 por turno)." },
        "El Cuerno de Urgok": { points: 30, faction: "comunes", relic: false, summary: "Portahechizos(6). Afecta unidades amigas a 18\".\nEn CaC ganan Odio. Si no, Inmunes a Miedo/Pánico y reagrupa huyendo." },
        "Alfombra de Arabya": { points: 30, faction: "comunes", relic: false, summary: "Volar. Sólo Infantería/Infantería Monstruosa. No puede unirse a unidades." },
        "Flauta de la Muerte": { points: 25, faction: "comunes", relic: false, summary: "Portahechizos(4). Maldición a 12\". Unidades enemigas -1L." },
        "Anillo de Oscuridad": { points: 25, faction: "comunes", relic: false, summary: "Un solo uso. Dura 1 turno. Sólo puede ser herido por ataques mágicos y sólo le impactan a 6+ en CaC." },
        "Poción de Curación Mayor": { points: 25, faction: "comunes", relic: false, summary: "Un solo uso. Restablece todas las heridas perdidas." },
        "Anillo del Fuego Infernal": { points: 25, faction: "comunes", relic: false, summary: "Portahechizos(3). Proyectil mágico 24\", 2D6 impactos F3 (sólo flamígeros)." },
        "Orbe de Tormenta": { points: 20, faction: "comunes", relic: false, summary: "Portahechizos(5). Maldición. Miniaturas con Volar/Flotar no pueden usarlo. En CaC, miniaturas con Volar/Flotar sólo le impactan a 6+." },
        "Botas de Celeridad": { points: 20, faction: "comunes", relic: false, summary: "Sólo Infantería/Infantería Monstruosa. Duplica Movimiento." },
        "El Corazón del Infortunio": { points: 20, faction: "comunes", relic: false, summary: "Al morir, plantilla grande. Miniaturas bajo ella sufren impacto F=R+1D3 y Heridas Múltiples(1D3)." },
        "Poción de Invisibilidad": { points: 20, faction: "comunes", relic: false, summary: "Un solo uso. Si está trabado, puede mover como si no lo estuviera." },
        "Poción de Fuerza": { points: 15, faction: "comunes", relic: false, summary: "Un solo uso. +3F hasta final de fase." },
        "Poción de Curación Menor": { points: 15, faction: "comunes", relic: false, summary: "Un solo uso. Restablece 1 herida perdida." },
        "Poción de resistencia": { points: 10, faction: "comunes", relic: false, summary: "Un solo uso. +3R hasta final de fase." },
        "Poción de Velocidad": { points: 10, faction: "comunes", relic: false, summary: "Un solo uso. +3I y Esquiva(5+) hasta final de fase." },
        "Icono de Grandeza": { points: 10, faction: "comunes", relic: false, summary: "Potencia de Unidad 10." },
        "Icono de Hierro": { points: 5, faction: "comunes", relic: false, summary: "Unidad gana Salvación Especial (6+) vs Máquinas de Guerra." },
        "Poción de Temeridad": { points: 5, faction: "comunes", relic: false, summary: "Un solo uso. Odio e Inmune a Psicología hasta inicio del siguiente turno." }
    },
    "Estandarte Mágico": {
        "Pabellón de Salvaguarda Arcana": { points: 35, faction: "comunes", relic: true, summary: "Unidad gana Resistencia Mágica(3). Si dispersa, 1 unidad enemiga a 24\" sufre 2D6 impactos F4." },
        "Pabellón de la Ira": { points: 40, faction: "comunes", relic: false, summary: "Portahechizos(4). Daño directo 24\", 1D6 impactos F5 que niegan TSA." },
        "Estandarte del Valor": { points: 35, faction: "comunes", relic: false, summary: "Unidad gana Sangre Fría." },
        "Estandarte de la Venganza": { points: 35, faction: "comunes", relic: false, summary: "Unidad gana Odio (Todos los enemigos)." },
        "Estandarte de Destrucción": { points: 30, faction: "comunes", relic: false, summary: "Unidad gana Poder de Penetración en CaC." },
        "Pabellón del Temor": { points: 25, faction: "comunes", relic: false, summary: "Unidad causa Miedo." },
        "Estandarte de la Maestría": { points: 25, faction: "comunes", relic: false, summary: "Unidad gana Golpe Maestro en CaC." },
        "Estandarte de Defensa": { points: 25, faction: "comunes", relic: false, summary: "Unidad gana +1 a TSA." },
        "Estandarte del Coraje": { points: 25, faction: "comunes", relic: false, summary: "Unidad repite chequeos de desmoralización y Pánico fallidos." },
        "Estandarte de la Rapidez": { points: 25, faction: "comunes", relic: false, summary: "Unidad gana +1M." },
        "Pabellón de Vitalidad": { points: 20, faction: "comunes", relic: false, summary: "Unidad gana Regeneración (6+)." },
        "Estandarte de Guerra": { points: 20, faction: "comunes", relic: false, summary: "Unidad gana +1 al resultado del combate." },
        "Estandarte de Disciplina": { points: 20, faction: "comunes", relic: false, summary: "Unidad gana +1L, pero no puede usar Presencia Inspiradora (salvo que el general esté en la unidad)." },
        "Estandarte de la Hechicería": { points: 20, faction: "comunes", relic: false, summary: "Unidad puede canalizar con +2 a la tirada." },
        "Estandarte de Protección Arcana": { points: 15, faction: "comunes", relic: false, summary: "Unidad gana Resistencia Mágica(1)." },
        "Estandarte Cazamonstruos": { points: 10, faction: "comunes", relic: false, summary: "Unidad inmune a Terror de Monstruos. Monstruos en CaC -1HA." },
        "Estandarte de la Llama Perpetua": { points: 10, faction: "comunes", relic: false, summary: "Unidad gana Ataques Flamígeros." }
    }
}

